services:
  crane:
    image: michaelsauter/golang:1.11
    rm: true
    interactive: true
    tty: true
    volume: [".:/crane"]
    workdir: /crane
    share-ssh-socket: true
    cmd: ["bash"]

commands:
  test: run crane make test
  build: run crane make build
  build-darwin: run crane make build-darwin
  gofmt: run crane gofmt -w crane

accelerated-mounts:
  crane:
    uid: 1000
    gid: 1000
