services:
  crane:
    image: michaelsauter/golang:1.8.3
    rm: true
    interactive: true
    tty: true
    volume: ["$GOPATH:/go"]
    workdir: /go/src/github.com/michaelsauter/crane
    cmd: ["bash"]

mac-syncs:
  "$GOPATH:/go":
    uid: 1000
    gid: 1000
    autostart: true
